### ISSUE TITLE
hb_mc_init_device() and device_launch() should accept memory buffer

### ISSUE THREAD

**Issue by cylinbao** [bespoke-silicon-group/bsg_f1#92]
https://github.com/bespoke-silicon-group/bsg_f1/blob/b15423845a81f05858d7e4061d47b4707237ff33/cl_manycore/libraries/bsg_manycore_driver.cpp#L432
https://github.com/bespoke-silicon-group/bsg_f1/blob/b15423845a81f05858d7e4061d47b4707237ff33/cl_manycore/libraries/bsg_manycore_driver.cpp#L842
These two functions take a string of a file location and load the binary from the file system.
But in some use cases, the binary will be in the memory already and we just want to pass the memory pointer to the function.
I think it will be better if this function can take memory pointer as input.
For the cases the binary is on the file system, maybe user just write some simple function to read it to the memory and pass it to the function.

[Reference: cuLaunchKernel](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__EXEC.html#group__CUDA__EXEC_1gb8f3dc3031b40da29d5f9a7139e52e15)

**Comment by drichmond** [comment]
@cylinbao Is this resolved in Borna's new API?

**Comment by cylinbao** [comment]
Hi thanks for addressing this.
This isn't resolved directly yet.
As here
https://github.com/bespoke-silicon-group/bsg_f1/blob/e48613ddb11c7b8d622653974e98211414927928/cl_manycore/libraries/bsg_manycore_cuda.cpp#L596
It still get file_path as input.
But it is solved in a lower level api with this
https://github.com/bespoke-silicon-group/bsg_f1/blob/e48613ddb11c7b8d622653974e98211414927928/cl_manycore/libraries/bsg_manycore_cuda.cpp#L638
Maybe @bornaehsani can add a program init function that calls hb_mc_loader_load() more straightly.

**Comment by bornaehsani** [comment]
Hi Chien-Yu! Thanks a lot for pointing this out. Yes this is still not implemented, which is why I have left it open for now. But I will implement it very soon.

**Comment by bornaehsani** [comment]
This issue is now addressed in PR #265 .
